apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: my-pull-secret
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: secrets/hello-world/rh-pull-secret
        metadataPolicy: None
        property: .dockerconfigjson
      secretKey: .dockerconfigjson
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: my-pull-secret
    template:
      type: kubernetes.io/dockerconfigjson
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: quay-secret
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: secrets/hello-world/quay
        metadataPolicy: None
        property: .dockerconfigjson
      secretKey: .dockerconfigjson
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: quay-secret
    template:
      type: kubernetes.io/dockerconfigjson
