kind: Namespace
apiVersion: v1
metadata:
  name: openbao
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openbao-eso-auth
  namespace: openbao
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-eso-to-openbao
  namespace: external-secrets
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: external-secrets
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: openbao
      ports:
        - protocol: TCP
          port: 8200
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-secret-store
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  provider:
    vault:
      server: 'http://openbao.openbao.svc.cluster.local:8200'
      path: kv
      version: v1
      auth:
        kubernetes:
          mountPath: kubernetes
          role: eso-role
          serviceAccountRef:
            name: openbao-eso-auth
            namespace: openbao
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: openbao
  namespace: openbao
spec:
  to:
    kind: Service
    name: openbao
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None