apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: openvsx
  labels:
    app: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: postgresql
  template:
    metadata:
      labels:
        app: openvsx
        deployment: postgresql
    spec:
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
      containers:
        - name: postgresql
          image: image-registry.openshift-image-registry.svc:5000/openshift/postgresql:15-el8
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRESQL_DATABASE
              value: openvsx
            - name: POSTGRESQL_USER
              value: openvsx
            - name: POSTGRESQL_PASSWORD
              value: openvsx
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/pgsql/data
          ports:
            - containerPort: 5432
              protocol: TCP
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 2Gi
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "openvsx"]
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "openvsx"]
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openvsx-server
  namespace: openvsx
  labels:
    app: openvsx-server
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: openvsx-server
  template:
    metadata:
      labels:
        deployment: openvsx-server
    spec:
      containers:
        - name: openvsx-server
          image: registry.redhat.io/devspaces/openvsx-rhel9:3.25
          imagePullPolicy: IfNotPresent
          readinessProbe:
            httpGet:
              path: /api/version
              port: 8080
            failureThreshold: 30
            initialDelaySeconds: 140
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /api/version
              port: 8080
            failureThreshold: 30
            initialDelaySeconds: 160
            periodSeconds: 20
            timeoutSeconds: 5
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 4Gi
          env:
            - name: GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: github-oauth
                  key: client-id
            - name: GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: github-oauth
                  key: client-secret
          volumeMounts:
            - name: extensions-storage
              mountPath: /tmp/extensions
      volumes:
      - name: extensions-storage
        persistentVolumeClaim:
          claimName: extensions-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ovsx-cli
  namespace: openvsx
  labels:
    app: ovsx-cli
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: ovsx-cli
  template:
    metadata:
      labels:
        deployment: ovsx-cli
    spec:
      containers:
        - name: ovsx-cli
          image: registry.redhat.io/devspaces/openvsx-rhel9:3.25
          imagePullPolicy: IfNotPresent
          env:
            - name: OVSX_REGISTRY_URL
              value: http://openvsx-server:8080
            - name: OVSX_PAT
              valueFrom:
                secretKeyRef:
                  name: ovsx-pat
                  key: token
          resources:
            requests:
              cpu: 20m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          command: ["/bin/sh", "-c"]
          args: ["tail -f /dev/null"]
