apiVersion: v1
kind: Namespace
metadata:
  name: openshift-devspaces
  annotations:
    argocd.argoproj.io/sync-wave: "0"
---
apiVersion: v1
kind: Namespace
metadata:
  name: openvsx
  labels:
    name: openvsx
  annotations:
    argocd.argoproj.io/sync-wave: "0"
