apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: openvsx
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: extensions-pvc
  namespace: openvsx
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
