apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: openvsx
  namespace: openvsx
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  to:
    kind: Service
    name: openvsx-server
    weight: 100
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
