apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-deploy
  namespace: shared-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: hello-world-deploy
  project: shared-app-project
  source:
    directory:
      recurse: true
    path: devops/manifests/applications/helloworld-ear/deploy
    repoURL: 'https://github.com/shirodkar/my-gitops.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
  ignoreDifferences:
    - kind: ServiceAccount
      jsonPointers:
        - /imagePullSecrets