apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-infra
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    directory:
      recurse: true
    path: manifests/infra
    repoURL: 'https://github.com/shirodkar/helloworld-ear.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
  ignoreDifferences:
    - kind: ServiceAccount
      jsonPointers:
        - /imagePullSecrets