kind: ConfigMap
apiVersion: v1
metadata:
  name: postgres-config
data:
  POSTGRESQL_JNDI: 'java:jboss/datasources/PostgreSQLDS'
  POSTGRESQL_URL: 'jdbc:postgresql://postgres:5432/postgres'
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: keystore-config
data:
    HTTPS_KEYSTORE: keystore.jks
    HTTPS_KEYSTORE_DIR: /etc/secrets/keystore/
    HTTPS_KEYSTORE_TYPE: JKS