kind: ServiceAccount
apiVersion: v1
metadata:
  name: eap-service-account
  namespace: hello-world-deploy
imagePullSecrets:
  - name: quay-secret
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: collector
  namespace: openshift-logging