apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mta
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    repoURL: 'https://github.com/shirodkar/my-gitops.git'
    targetRevision: HEAD
    path: manifests/plain/mta
    directory:
      recurse: true
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - SkipDryRunOnMissingResource=true