kind: Deployment
apiVersion: apps/v1
metadata:
  name: honey-bees-quarkus-backend
  labels:
    app: honey-bees-quarkus-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: honey-bees-quarkus-backend
  template:
    metadata:
      labels:
        app: honey-bees-quarkus-backend
        deployment: honey-bees-quarkus-backend
    spec:
      imagePullSecrets:
        - name: quay-secret
      containers:
        - name: honey-bees-quarkus-backend
          image: 'quay.io/rh_ee_sshirodk/honey-bees-quarkus-backend:latest'
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
          resources:
            limits:
              memory: 512Mi
              cpu: 500m
            requests:
              memory: 256Mi
              cpu: 250m