kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: honey-bees-quarkus-backend
spec:
  to:
    kind: Service
    name: honey-bees-quarkus-backend
    weight: 100
  port:
    targetPort: 8080-tcp