apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: hello-world-app-project
  namespace: shared-gitops
spec:
  clusterResourceBlacklist:
    - group: '*'
      kind: '*'
  description: Hello World App Project
  destinations:
    - namespace: '*'
      server: '*'
  namespaceResourceBlacklist:
    - group: ''
      kind: ResourceQuota
    - group: ''
      kind: LimitRange
    - group: operators.coreos.com
      kind: '*'
    - group: operator.openshift.io
      kind: '*'
    - group: storage.k8s.io
      kind: '*'
  sourceRepos:
    - 'https://github.com/shirodkar/helloworld-ear'
  roles:
    - description: Developer
      groups:
      - developers
      name: devops-admin
      policies:
      - p, proj:hello-world-app-project:devops-admin, applications, *, hello-world-app-project/*, allow
      - p, proj:hello-world-app-project:devops-admin, exec, create, hello-world-app-project/*, allow