apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  name: external-secrets-operator-og
  namespace: external-secrets-operator
spec: {}
---
apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  name: openshift-logging-og
  namespace: openshift-logging
spec: {}
