apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: my-syslog-vm
  namespace: hello-world-logging
spec:
  dataVolumeTemplates:
    - metadata:
        name: my-syslog-vm-volume
      spec:
        sourceRef:
          kind: DataSource
          name: rhel10
          namespace: openshift-virtualization-os-images
        storage:
          resources:
            requests:
              storage: 30Gi
  instancetype:
    kind: virtualmachineclusterinstancetype
    name: u1.medium
  preference:
    kind: virtualmachineclusterpreference
    name: rhel.10
  runStrategy: Always
  template:
    metadata:
      annotations:
        kubevirt.io/pci-topology-version: v3
      labels:
        network.kubevirt.io/headlessService: headless
    spec:
      architecture: amd64
      domain:
        devices:
          autoattachPodInterface: false
          disks:
            - bootOrder: 1
              name: rootdisk
          interfaces:
            - macAddress: '02:60:7a:5e:31:15'
              masquerade: {}
              name: default
        firmware:
          serial: 2d766745-c075-447c-bd9b-6c9db85d4e1e
          uuid: 3c0137f7-1b5d-4141-9017-3a0622e67274
        machine:
          type: pc-q35-rhel9.6.0
        resources: {}
      networks:
        - name: default
          pod: {}
      subdomain: headless
      volumes:
        - dataVolume:
            name: my-syslog-vm-volume
          name: rootdisk
        - cloudInitNoCloud:
            userData: |
              #cloud-config
              chpasswd:
                expire: false
              password: fky4-0we3-8iwz
              user: rhel
          name: cloudinitdisk
---
kind: Service
apiVersion: v1
metadata:
  name: headless
  namespace: hello-world-logging
spec:
  ports:
    - name: headless
      protocol: TCP
      port: 5434
      targetPort: 5434
    - name: udp
      protocol: UDP
      port: 514
      targetPort: 514
  type: ClusterIP
  selector:
    network.kubevirt.io/headlessService: headless