apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-s2i
  namespace: shared-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: hello-world-s2i
  project: shared-app-project
  source:
    directory:
      recurse: true
    path: manifests/kustomize/applications/helloworld-ear/s2i
    repoURL: 'https://github.com/shirodkar/my-gitops.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true