apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-app-of-apps
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    directory:
      recurse: true
    path: gitops/app-of-apps/apps
    repoURL: 'https://github.com/shirodkar/helloworld-ear.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true