kind: Namespace
apiVersion: v1
metadata:
  name: external-secrets-operator
  annotations:
    argocd.argoproj.io/sync-wave: "0"
---
kind: Namespace
apiVersion: v1
metadata:
  name: openshift-logging
  annotations:
    argocd.argoproj.io/sync-wave: "0"
---
kind: Namespace
apiVersion: v1
metadata:
  name: hello-world-logging
  annotations:
    argocd.argoproj.io/sync-wave: "0"
---
{{- range .Values.namespaces }}
---
kind: Namespace
apiVersion: v1
metadata:
  name: {{ . }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
{{- end }}
