kind: Namespace
apiVersion: v1
metadata:
  name: external-secrets-operator
---
kind: Namespace
apiVersion: v1
metadata:
  name: openshift-logging
---
kind: Namespace
apiVersion: v1
metadata:
  name: hello-world-logging
---
kind: Namespace
apiVersion: v1
metadata:
  name: openbao
{{- range .Values.namespaces }}
---
kind: Namespace
apiVersion: v1
metadata:
  name: {{ . }}
{{- end }}
