apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-credentials
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: secrets/hello-world/postgres
        metadataPolicy: None
        property: POSTGRESQL_PASSWORD
      secretKey: POSTGRESQL_PASSWORD
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: secrets/hello-world/postgres
        metadataPolicy: None
        property: POSTGRESQL_USER
      secretKey: POSTGRESQL_USER
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: postgres-credentials
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keystore-credentials
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: secrets/hello-world/keystore
        metadataPolicy: None
        property: HTTPS_PASSWORD
      secretKey: HTTPS_PASSWORD
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: keystore-credentials
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keystore
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: Auto
        key: secrets/hello-world/keystore-file
        metadataPolicy: None
        property: keystore.jks
      secretKey: keystore.jks
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: keystore
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: quay-secret
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: secrets/hello-world/quay
        metadataPolicy: None
        property: .dockerconfigjson
      secretKey: .dockerconfigjson
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: quay-secret
    template:
      type: kubernetes.io/dockerconfigjson