apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kai-api-keys
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: secrets/ai
        metadataPolicy: None
        property: API_KEY
      secretKey: API_KEY
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: secrets/ai
        metadataPolicy: None
        property: API_KEY
      secretKey: OPENAI_API_KEY
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: kai-api-keys